version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s\\%(name)s:\t%(message)s"

handlers:
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: debug.log  # Prepended with correct directory in application code
    maxBytes: 3145728 # 3MB
    backupCount: 2
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log  # Prepended with correct directory in application code
    maxBytes: 3145728 # 3MB
    backupCount: 0
    encoding: utf8

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

root:
  level: WARNING  # All loggers to be WARNING by default
  handlers: [debug_file_handler, info_file_handler, console]
